GLOBAL.setfenv(1, GLOBAL)

STRINGS.SKIN_NAMES.snowball_item_dungball = "粪球"
STRINGS.SKIN_DESCRIPTIONS.snowball_item_dungball = "这雪球，一股子臭烘烘的味儿。"

STRINGS.CHARACTERS.GENERIC.I_MESSED_UP = "我搞砸了！"
STRINGS.CHARACTERS.GENERIC.TRY_MY_SNOWBALL = "试试我的雪球！"
STRINGS.CHARACTERS.GENERIC.BIG_SNOWBALL_IS_COMMING = "大雪球来了！"
